[unstable]
build-std = ["core"]
#build-std-features = ["panic_immediate_abort"]

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip nrf5340_xxAA --allow-erase-all"

[build]
target = "thumbv8m.main-none-eabihf"

[env]
DEFMT_LOG = "debug,nrf70=debug"
